### ISSUE TITLE
Newer Adoptium JDKs are not detected

### ISSUE THREAD

**Issue by ChargedByte** [MultiMC/Launcher#4200]
### Operating System

Windows

### Description of bug

Newer builds/versions of the Adoptium JDK are not automatically detected.

### Steps to reproduce

- Install latest (at the time of writing) _8u312-b07_ or _11.0.13+8_ JDK from Adoption
- JDK installation is not auto-detected

The installation folder is like this:
`C:\Program Files\Eclipse Adoptium\jdk-8.0.312.7-hotspot`

The registry key is like this:
`SOFTWARE\Eclipse Adoptium\JDK\8.0.312.7\hotspot\MSI`

NOTE: Latest JDK 17 build _17+35_ does not seem to be affected.

### Suspected cause

Adoptium team is changing the vendor name from "Eclipse Foundation" to "Eclipse Adoptium".

This has changed the default install folder and registry key to "Eclipse Adoptium".

References:
adoptium/installer#352
adoptium/installer#347
adoptium/installer#350

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by NewoIsTaken** [comment]
@ChargedByte, if you could test PR #4231, if that solves your issue, that would be appreciated.

**Comment by NewoIsTaken** [comment]
This problem should be resolved now.

**Comment by peterix** [comment]
Yep.

**Comment by VolatileCable** [comment]
I just tried the new MultiMC release and sadly this is not fully fixed, it only detects the JDK versions but not the much smaller JRE releases that are available for Adoptium 8 and 11 LTS. This might have gone unnoticed as only the JDK version is provided for Adoptium 17 anymore.

The code needs to additionally check HKLM\SOFTWARE\Eclipse Adoptium\JRE

**Comment by NewoIsTaken** [comment]
@VolatileCable, thanks for the bug report! That is noted. I will submit a pull request tonight if I have time.
