### ISSUE TITLE
XBox user authentication failed.

### ISSUE THREAD

**Issue by MrLeoOfficial** [MultiMC/Launcher#4506]
### Operating System

Windows

### Description of bug

This afternoon, MultiMC marked all of my accounts as expired, even though I just played Minecraft the night before. After trying to get logged in via my Microsoft Account (that always worked before), it would give me this error:
_**XBox user authentication failed.**_
Please help me as soon as you can. 

If you need to contact me, here is my discord: MrLeo#2298

Here is a screenshot of the error:
![image](https://user-images.githubusercontent.com/99419084/153449700-b2832446-192a-4421-802f-e184741a2839.png)

### Bug

- _**XBox user authentication failed.**_

### Suspected cause

I think that it doesn't work because, before playing last night I didn't use my computer for about 2 weeks. Even though this is the problem, I don't know how to resolve it.

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jonatjano** [comment]
same issue on Linux, my logs are globally the same as nove93 with a little difference after the negative answer from microsoft
```
  403.505 D "device_code" :  "[REDACTED]"
  403.505 D "expires_in" :  "900"
  403.505 D "interval" :  "5"
  403.505 D "message" :  "Pour vous connecter, utilisez un navigateur web pour ouvrir la page https://www.microsoft.com/link et entrez le code [REDACTED] pour vous authentifier."
  403.505 D "user_code" :  "[REDACTED]"
  403.505 D "verification_uri" :  "https://www.microsoft.com/link"
  403.505 D DeviceFlow::onDeviceAuthReplyFinished: Device auth request response
  403.505 D DeviceFlow::startPollServer: device_ and user_code expires in 900 seconds
  428.947 D PollServer::onPollTimeout: retrying
  433.947 D PollServer::onPollTimeout: retrying
  438.947 D PollServer::onPollTimeout: retrying
  439.420 D DeviceFlow::onVerificationReceived: Emitting closeBrowser()
  439.420 D DeviceFlow::onVerificationReceived: Access token returned for implicit or device flow
  439.420 D DeviceFlow::onVerificationReceived: Token expires in 3600 seconds
  439.420 D DeviceFlow::setLinked: true
  439.420 D AuthFlow: "Logging in as an Xbox user."
  439.420 D First layer of XBox auth ... commencing.
  439.754 W AuthRequest::onRequestError: Error 302
  439.754 W AuthRequest::onRequestError: Error string:  "Error transferring https://user.auth.xboxlive.com/user/authenticate - server replied: Bad Request"
  439.754 W AuthRequest::onRequestError: HTTP status 400 "Bad Request"
  439.754 W Reply error: 302
  439.754 C Task "MSAInteractive(0x1d8d070)" failed:  "XBox user authentication failed."
  442.297 W QCoreApplication::postEvent: Unexpected null receiver
  507.160 D Task "MSAInteractive(0x1a1f3d0)" starting for the first time
  507.160 D AuthFlow: "Logging in with Microsoft account."
  507.160 D DeviceFlow::link
  507.160 D DeviceFlow::setLinked: false
  507.504 D DeviceFlow::onDeviceAuthReplyFinished
  507.504 D DeviceFlow::onDeviceAuthReplyFinished: Tokens returned:
  
```

**Comment by BackgroundPony** [comment]
Not a Multimc issue. Works now, probably xbox live auth hiccup

**Comment by FlooferLand** [comment]
Same happening here. I've had this happen twice in a row even after restarting MultiMC
Might be a Microsoft issue (?). Their servers have been extremely horrible towards me (opening minecraft.net gives me an "Access Denied" error 99% of the time) so that could be it.

**Comment by Fixer-007** [comment]
I have the same problem with multimc dev build 3198

**Comment by Brokkonaut** [comment]
Same issue here, logging in with the official launcher worked for me so it might me a MultiMC issue or just random outages of the xbox login service

**Comment by ItzSave** [comment]
Been having this issue as well just started happening today.

**Comment by Fixer-007** [comment]
I've managed to readd MSA account in multimc just now and it runs fine now for me. Try it.

**Comment by MrRedstoneA1** [comment]
I managed to fix this issue by updating multimc to a developer version. But it also broke the world that I played last. I already made a bug ticket about that.

**Comment by phit** [comment]
closing as the temporary xbox outage has been resolved

**Comment by MelDaBigBoss** [comment]
> Not a MultiMC issue. Works now (for me), probably Xbox Live Auth hiccup. Some are still having issues, though

Yeah i still have this issue. I can't log in. Even though I know my account is vaild

**Comment by SlavicGuyTheMaster** [comment]
Guys i know a fix u need to go to 

c:\Windows\System32\Drivers\etc\hosts.
and select notepad or any other txt editor
 and remove these lines:
127.0.0.1 xboxlive.com
127.0.0.1 user.auth.xboxlive.com
127.0.0.1 presence-heartbeat.xboxlive.com

let me know if it worked!

**Comment by MelDaBigBoss** [comment]
> Guys i know a fix u need to go to
> 
> c:\Windows\System32\Drivers\etc\hosts. and select notepad or any other txt editor and remove these lines: 127.0.0.1 xboxlive.com 127.0.0.1 user.auth.xboxlive.com 127.0.0.1 presence-heartbeat.xboxlive.com
> 
> let me know if it worked!

What if you are trying to use MultiMC with a school controlled PC that won't let you save the text file in the drivers folder. Can you just do it in the Document or will it not work?

**Comment by ramyILG** [comment]
**My host file don't show any line about xboxlive :**

> # Copyright (c) 1993-2009 Microsoft Corp.
> #
> # This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
> #
> # This file contains the mappings of IP addresses to host names. Each
> # entry should be kept on an individual line. The IP address should
> # be placed in the first column followed by the corresponding host name.
> # The IP address and the host name should be separated by at least one
> # space.
> # Additionally, comments (such as these) may be inserted on individual
> # lines or following the machine name denoted by a '#' symbol.
> #
> # For example:
> #
> #      102.54.94.97     rhino.acme.com          # source server
> #       38.25.63.10     x.acme.com              # x client host
> 
> # localhost name resolution is handled within DNS itself.
> #	127.0.0.1       localhost
> #	::1             localhost
>

**Comment by ramyILG** [comment]
**My host file don't show any line about xboxlive :**
![image](https://user-images.githubusercontent.com/96911049/172240813-d17b03cb-7ed8-4c5b-9412-ed47c3425b3a.png)

**Comment by Brokkonaut** [comment]
That comment was incorrect, the hosts file usually is no problem.

**Comment by ramyILG** [comment]
@Brokkonaut 
So what should I do to fix this issue

**Comment by Adu-3** [comment]
I have used Prism Launcher which is a fork from MultiMC but the issue is the same .

For those who are still facing the issue , the problem seems to be a compatibility issue that the launcher can't deal with Xbox in some login steps. 

To fix this just login form the official launcher Minecraft launcher and then go back and login from MultiMC 
this has solved it for me :)

**Comment by Frxgxd** [comment]
> Adu-3

give link to the official luancher login

**Comment by Frxgxd** [comment]
> Same issue here, logging in with the official launcher worked for me so it might me a MultiMC issue or just random outages of the xbox login service

give link to official launcher

**Comment by benkusu** [comment]
Is the answer out? Helppp

**Comment by mpsijm** [comment]
> To fix this just login form the official launcher Minecraft launcher and then go back and login from MultiMC

Works for me too, life-saver! :heart:

@Frxgxd The official launcher can be downloaded from www.minecraft.net (be sure to download the launcher for the Java version) :slightly_smiling_face: 

@MultiMC, I'm not sure if Adu-3's "workaround" can be added to the error message, just in case?

**Comment by noanookie** [comment]
Had the same problem (with Prism Launcher), I just went to their website and downloaded the installer, ran it and working fine after that.

**Comment by shpaass** [comment]
I'm having the same issue. Firefox 112.0.2, Windows 11.
Throughout several days, it doesn't work initially and then eventually logs in after the usual linking steps.

**Comment by tarneaux** [comment]
For anyone still experiencing this issue, switching the java version from 20.0.1 to 1.8 fixed it immediately on Arch Linux.

**Comment by Maestries** [comment]
Hello, I just had the issue and searched a little on that error on the Internet. 

I solved my problem by updating my Java version (was on Java JDK 17.0.6 and installed 17.0.7) juste after that, it solved my issue with the authentication of the account. 

I hop this can helps some of you.

**Comment by phit** [comment]
Java version has nothing to do with any of this, just intermittent issues on Microsoft's end, waiting would have had the same effect..

**Comment by Maestries** [comment]
> Java version has nothing to do with any of this, just intermittent issues on Microsoft's end, waiting would have had the same effect..

Well, that's possible, i can't argue with that. possibly it was just waiting the solution indeed.

**Comment by er1nulla** [comment]
I had this error. On Windows, I just logged into minecraft.net and microsoft store with my account. This problem is clearly related to authentication. Try also.

**Comment by rechkagmod** [comment]
I think i found how to fix it

I've download MultiMC 5 (latest 5 version) and updated it.After updating im tried to login and i succsesfully logged in!
Try this one,i hope you can login like me.

**Comment by Zane2b2t** [comment]
i had this thinking it's only my issue. but then when i told my friends i have an issue they said "same. can't login"
so it's not multimc its from xbox

**Comment by dlabaja** [comment]
glad I'm not the only one not experiencing this, and since I have nothing new to this to say - don't support them and use Linux ;)

**Comment by phit** [comment]
https://twitter.com/mojangstatus/status/1800101837304987819
https://bugs.mojang.com/browse/WEB-7179

**Comment by SrIzan10** [comment]
if you don't have a password set, please set a password on your microsoft account. this has fixed my friend's login
