### ISSUE TITLE
NeoForge Support Tracking Issue

### ISSUE THREAD

**Issue by Khitiara** [MultiMC/Launcher#5232]
This issue serves as a tracking issue for adding support for [NeoForge](https://neoforged.net), a fork of MinecraftForge which for the moment maintains compatibility but may diverge in the future. Given the current maintained compatibility and possible future divergence, plus the new state of the NeoForged project, this seems the perfect time to work out how compatibility will be handled and add support in the launcher.

**Comment by Romaq** [comment]
A search for https://duckduckgo.com/?q=multimc+neoforge&ia=web led me here, and I did find https://neoforged.net/. Unfortunately, I'm hitting a bit of "clueless newbie ruins ALL THE THINGS" feeling to try to use the install on a Multicraft instance. Is this discussed on a forum or on a web page? Is MultiMC open to including NeoForge as an option? Are these questions part of this specific GITHUB issue, or is there a more appropriate location, perhaps in the forum? I'm looking for "sweet and gentle hand holding" I *want* to support you, I just have my existing client and server situation, and I'd like to be sure I can make that change without fouling the MultiMC client instances and the server my friends and I are playing on.

**Comment by Khitiara** [comment]
> A search for https://duckduckgo.com/?q=multimc+neoforge&ia=web led me here, and I did find https://neoforged.net/. Unfortunately, I'm hitting a bit of "clueless newbie ruins ALL THE THINGS" feeling to try to use the install on a Multicraft instance. Is this discussed on a forum or on a web page? Is MultiMC open to including NeoForge as an option? Are these questions part of this specific GITHUB issue, or is there a more appropriate location, perhaps in the forum? I'm looking for "sweet and gentle hand holding" I _want_ to support you, I just have my existing client and server situation, and I'd like to be sure I can make that change without fouling the MultiMC client instances and the server my friends and I are playing on.

neoforge is not yet supported by multimc, this issue exists to track progress on making that happen

**Comment by Romaq** [comment]
Thank you! When we start a new map, I offer everyone a working MultiMC instance to download so they don't have to do anything. For updates, I'm offering a mods.zip folder to download and replace their existing mods folder UNLESS they savey enough to manage the mod updates themselves as well as choose what they wish. It's ok if it takes a while to get MultMC in. That also gives time for NeoForge to iron things out.

**Comment by Speiger** [comment]
Ok its been almost half a year.
Neoforge has established itself quite well at this point, and i wondered.
If i want to test my neo release builds do i need to drop MultiMC or is the support for this coming?
Because at this point what is the reason for the delay?

**Comment by Romaq** [comment]
My "game group" consisting of my wife and a few friends are currently enjoying Ark Survival Ascended, but sooner or later we will become bored with that game, and likely take up TerraFirmaCraft for Forge 1.20.1. I *DO* understand things become "complicated" since the relationship between MultiMC and any *OTHER* Mod Loader project isn't necessarily straightforward. That said, I'm in no rush to return to Minecraft. I'm really holding out for TFC over MultiMC for deployment as NeoForge. MultiMC has been a GODSEND for members of the group who are not technically inclined. And an entirely fresh start using NeoForge for production would be far better than bailing on Forge in the middle of a map session given the server dynamics.

So yeah... I'm keeping a close eye on this one. :)

**Comment by burningtnt** [comment]
It would be great if the UID of NeoForge could be determined as soon as possible.

**Comment by Menion2k** [comment]
I am unable to install NeoForge from MMC 0.7.0
I get:

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance 1.20.1 - test' failed to process:
https://maven.neoforged.net/net/neoforged/forge/1.20.1-47.1.5/forge-1.20.1-47.1.5-installer.jar

Java is 21

**Comment by FeedTheChunk** [comment]
> Java is 21

Use Java 17.  https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by Menion2k** [comment]
> > Java is 21
> 
> Use Java 17. https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

Same issue
The maven artifactory address is now different, there is a /#/release now, it should be:

https://maven.neoforged.net/#/release/net/neoforged/forge/1.20.1-47.1.5/forge-1.20.1-47.1.5-installer.jar

**Comment by burningtnt** [comment]
> https://maven.neoforged.net/#/release/net/neoforged/forge/1.20.1-47.1.5/forge-1.20.1-47.1.5-installer.jar

That's the URL of NeoForge Maven Web UI, instead of the actual url pointed to the file.

`https://maven.neoforged.net/release/net/neoforged/forge/1.20.1-47.1.5/forge-1.20.1-47.1.5-installer.jar` is the correct one.

**Comment by Menion2k** [comment]
> > https://maven.neoforged.net/#/release/net/neoforged/forge/1.20.1-47.1.5/forge-1.20.1-47.1.5-installer.jar
> 
> That's the URL of NeoForge Maven Web UI, instead of the actual url pointed to the file.
> 
> `https://maven.neoforged.net/release/net/neoforged/forge/1.20.1-47.1.5/forge-1.20.1-47.1.5-installer.jar` is the correct one.

Well but if you click it you get error 404, don't you?

**Comment by burningtnt** [comment]
> Well but if you click it you get error 404, don't you?

```
https://maven.neoforged.net/releases/net/neoforged/forge/1.20.1-47.1.5/forge-1.20.1-47.1.5-installer.jar
                                   ^
```
My fault. I forget to add an 's'

**Comment by Menion2k** [comment]
> > Well but if you click it you get error 404, don't you?
> 
> ```
> https://maven.neoforged.net/releases/net/neoforged/forge/1.20.1-47.1.5/forge-1.20.1-47.1.5-installer.jar
>                                    ^
> ```
> 
> My fault. I forget to add an 's'

Confirm same issue with Java 17 (sorry I switched to italian, but the error is the same). I can download the jar manually. Can I place them somewhere so MMC does not attempt to download?

Checking Java version...
Java is version 17.0.10, using 64-bit architecture, from Oracle Corporation.


Aggiornamento dell'istanza fallito perché: Aggiornamento di gioco fallito: impossibile recuperare le librerie richieste.
Causa:
Impossibile elaborare l'attività 'Librerie per l'istanza 1.20.1 - test':
https://maven.neoforged.net/net/neoforged/forge/1.20.1-47.1.105/forge-1.20.1-47.1.105-installer.jar

**Comment by Menion2k** [comment]
Actually it can download just fine for 1.20.6, the problem seems to be relative to 1.20.1

**Comment by phit** [comment]
yeah they retroactively updated their installers and multimcs meta for those versions needs to be invalidated

**Comment by HGTorin** [comment]
I've got a server fully set up for 1.20.1, and ViaForge doesn't seem to want to play nicely, nor other mods for that matter on newer versions (1.20.4). Is the issue with NeoForge not liking specifically this version able to be fixed either clientside or MultiMC/Neoforge side?

**Comment by MakkuroJoKeRGod** [comment]
> Actually it can download just fine for 1.20.6, the problem seems to be relative to 1.20.1

I'm still encountering this very issue in the latest version of MultiMC, using Java 17.
Should the issue be re-opened?

**Comment by phit** [comment]
they broke it again, known and will be fixed once someone with permission to do so gets around to it.. keep an eye on https://github.com/MultiMC/meta-multimc/commits/master/ for a fix

**Comment by Menion2k** [comment]
Actually in another installation it works. It is like some internal
metadata gets corrupted or similar

Il Mer 3 Lug 2024, 18:53 Philip T. ***@***.***> ha scritto:

**Comment by VioletSkies19** [comment]
is this supposed to be fixed? still getting this error
```

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance a' failed to process:
https://maven.neoforged.net/net/neoforged/neoforge/20.4.237/neoforge-20.4.237-installer.jar
```

**Comment by jakint0sh** [comment]
Got this trying to install neoforge today, I take it 1.20.1 in particular is still borked?
Trimmed log:
```
MultiMC version: 0.7.0-3860
Java path is:
/usr/lib/jvm/java-21-openjdk-amd64/bin/java


Checking Java version...
Java is version 21.0.3, using 64-bit architecture, from Ubuntu.


Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance smp modded' failed to process:
https://maven.neoforged.net/net/neoforged/forge/1.20.1-47.1.106/forge-1.20.1-47.1.106-installer.jar
```
I should note that I get the same failure under Java 17, 19, and 21.

**Comment by Puppyguarb** [comment]
I also get this issue on minecraft 1.20.1.
```
Checking Java version...
Java is version 17.0.1, using 64-bit architecture, from Oracle Corporation.


Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance Direwolf20 120' failed to process:
https://maven.neoforged.net/net/neoforged/forge/1.20.1-47.1.106/forge-1.20.1-47.1.106-installer.jar
```

MultiMC version is 0.7.0-3863. @peterix you may want to reopen this issue.

**Comment by phit** [comment]
for the record newer versions work fine, its just that meta for older version needs to be refreshed since neoforge rereleased all versions at some point with new hashes

**Comment by Helcostr** [comment]
> for the record newer versions work fine, its just that meta for older version needs to be refreshed since neoforge rereleased all versions at some point with new hashes

@phit this is the first time for me in dealing with this issue and I see what you mean: fixing the SHA1 hash to what it is currently now for the file `neoforge-20.4.237-installer.jar` allows me to launch via MultiMC.

However, does the root problem lie with Neoforge, as they need to update a file, or does MultiMC have a badly cached version of the hashes?

**Comment by phit** [comment]
multimc "caches" all files to protect you and the launcher from brokenness, so in this case they need to be refreshed manually
https://github.com/MultiMC/meta-upstream

**Comment by Helcostr** [comment]
Should we then submit a new update via a fork? I could crawl through the servers and re-hash everything...

Or will someone else take care of that?

**Comment by phit** [comment]
its all automated via https://github.com/MultiMC/meta, currently waiting on peterix to fix it, he is the one with access to the repos

**Comment by Helcostr** [comment]
(So Pull Requesting a fork of the repo with the updated hashes wont accelerate the process, I see)

**Comment by liquidthex** [comment]
Bump for any update on this?

**Comment by phit** [comment]
was fixed here https://github.com/MultiMC/meta-multimc/commit/8ec84c357d0f039a80d27c68eca53f0c376c73f8

**Comment by shingle-bells** [comment]
It looks like this issue is happening again with Minecraft 1.20.1, however changing the hash and size manually by editing net.neoforged.json does not fix the issue from the looks of things. When going to the URL linked in the JSON file, I get a 404 error which seems to suggest the files have been either moved or removed.

**Comment by Romaq** [comment]
> It looks like this issue is happening again with Minecraft 1.20.1, 

I'm unable to have NeoForge 26.* install to MC 26.* clients. Fabric updates install fine. I did confirm NeoForge installs on MC 1.20.1 for me. I'm still trying to understand how NeoForge fits into the MultiMC ecosystem. I also note the NeoForge web page comes up with 26.1.2.6-beta, and I'm not clear if "beta" status has anything to do with this.
