### ISSUE TITLE
"Authentication tokens expired" every single time

### ISSUE THREAD

**Issue by azurit3lol** [MultiMC/Launcher#5620]
### Description of bug

![Image](https://github.com/user-attachments/assets/8c4fb44a-5cd9-4d22-b4a7-2fb2869404fa)

### Steps to reproduce

whenever i try to log in myself, even consistently i always get this message.

### Suspected cause

I literally don't know.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by OmegaHaxors** [comment]
You've got it good, your account requires reauthentication, mine it just flat out deleted my account and gives me a
Failed to get authorization for Xbox services. Error %2.
every time I try to log back in. Can't even play offline until Xbox recovers from whatever terror attack or lapse of competency is causing their servers to mess up again this time, which is just astoundingly good design. Love how a tiny mistake that I can't predict or do anything about just completely prevents me from launching a single player game, and I especially love just how often it happens. Love being treated no different to a pirate because of something that isn't even my fault and I can't do anything about.

Seriously, why delete accounts when the authentication fails? That's just needlessly controlling behavior.

**Comment by phit** [comment]
yes mojang adjusted their rate limiting for various things, and multimc is not handling it well, see all the other linked issues

**Comment by phit** [comment]
also related to https://github.com/MultiMC/Launcher/issues/5463
this used to only happen when you had a lot of accounts, now this can happen frequently with just one account

**Comment by Girtana1** [comment]
> Love being treated no different to a pirate because of something that isn't even my fault and I can't do anything about.

You think that's bad? About 5 years ago now I tried resetting the password on my account, every time I would do so I would never actually get the reset request email. So I contact support of course, they tell me that MY email that's associated with MY account was NOT proof that I actually owned the game. They seriously somehow wanted me to provide a receipt for a gift card that I bought in person in 2013 with cash... Eventually after bitching long enough the password reset request function just MAGICALLY started working again and I was able to get back into my account, funny how that works eh? 

This is a huge reason of why it urks me so much that the vast majority of people in various Mc communities will strictly advocate against pirating the game, why do you care?? I'll never be mad at notch for getting out of this nonsense at the perfect time, I will however forever be salty at him for leaving us with the management and support of a multi-billion dollar corporation lol.

**Comment by TimBuildIt** [comment]
anyone gonna fix this or are we just going to link all the issues to each other so you go in a circle and end up back here?

**Comment by redtailcowboy** [comment]
Fixed:

You have to sign into the official Minecraft launcher, don't even need to launch the game. Next MultiMC sign in will work!

**Comment by qantonp** [comment]
> Fixed:
> 
> You have to sign into the official Minecraft launcher, don't even need to launch the game. Next MultiMC sign in will work!


I am logged into the official launcher but still have the same issue as before. The authentication token is expired and I have to sign in again.

**Comment by giteliot** [comment]
Same issue, I log in with my Microsoft account and immediately the token is expired. Over and over. No known workarounds?
